
[build]
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for SEO and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.gpteng.co; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: images.unsplash.com; font-src 'self' fonts.gstatic.com fonts.googleapis.com; connect-src 'self';"
